apiVersion: apps/v1
kind: Deployment
metadata:
  name: portkey
  namespace: portkey
  labels:
    app: portkey
spec:
  selector:
    matchLabels:
      app: portkey
  replicas: 12
  template:
    metadata:
      labels:
        app: portkey
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: portkey
        image: portkeyai/gateway:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1
            memory: "2Gi"
          limits:
            cpu: 1
            memory: "3Gi"
        ports:
        - containerPort: 8787
      nodeSelector:
        "alpha.eksctl.io/nodegroup-name": "node-ai-gateway"

