apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: litellm-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
parameters:
  fsType: ext4
  type: gp3
reclaimPolicy: Delete
allowVolumeExpansion: true
