image:
  repository: kong/kong-gateway
  tag: "3.10"

enterprise:
  enabled: true
  license_secret: kong-enterprise-license

proxy:
  enabled: true
  type: LoadBalancer
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
    "service.beta.kubernetes.io/aws-load-balancer-nlb-target-type": "ip"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=false
      

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false

manager:
  enabled: false

portal:
  enabled: false

portalapi:
  enabled: false

env:
  role: data_plane
  database: "off"
  cluster_control_plane: "kong-cp-kong-cluster.kong-cp.svc.cluster.local:8005"
  cluster_telemetry_endpoint: "kong-cp-kong-clustertelemetry.kong-cp.svc.cluster.local:8006"
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  vitals: "off"
  nginx_worker_processes: "4"
  upstream_keepalive_max_requests: "100000"
  nginx_http_keepalive_requests: "100000"
  nginx_http_client_body_buffer_size: 5m
  proxy_access_log: "off"
  dns_stale_ttl: "3600"
  log_level: notice

replicaCount: 3
  

ingressController:
  enabled: false
  installCRDs: false

resources:
  requests:
    cpu: 1
    memory: "2Gi"
  limits:
    cpu: 4
    memory: "3Gi"

status:
  enabled: true
  http:
    enabled: true
  containerPort: 8100

serviceMonitor:
  enabled: true


nodeSelector:
  "alpha.eksctl.io/nodegroup-name": "node-ai-gateway"

