image:
  repository: kong/kong-gateway
  tag: "3.10"

enterprise:
  enabled: true
  license_secret: kong-enterprise-license

proxy:
  enabled: true
  type: LoadBalancer
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
    #"service.beta.kubernetes.io/aws-load-balancer-scheme": "internet-facing"
    "service.beta.kubernetes.io/aws-load-balancer-nlb-target-type": "ip"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=false
    #service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0488a3c804e0aaf62
      

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false

manager:
  enabled: false

portal:
  enabled: false

portalapi:
  enabled: false

env:
  role: data_plane
  database: "off"
  #cluster_mtls: pki
  cluster_control_plane: "kong-cp-kong-cluster.kong-cp.svc.cluster.local:8005"
  #cluster_server_name: "kong-cp-kong-cluster.kong-cp.svc.cluster.local"
  cluster_telemetry_endpoint: "kong-cp-kong-clustertelemetry.kong-cp.svc.cluster.local:8006"
  #cluster_telemetry_server_name: "kong-cp-kong-clustertelemetry.kong-cp.svc.cluster.local"
  #cluster_ca_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  #lua_ssl_trusted_certificate: system
  #konnect_mode: "on"
  vitals: "off"
  nginx_worker_processes: "4"
  upstream_keepalive_max_requests: "100000"
  nginx_http_keepalive_requests: "100000"
  nginx_http_client_body_buffer_size: 5m
  proxy_access_log: "off"
  dns_stale_ttl: "3600"
  log_level: notice
  #log_level: debug
  #log_level: warn
  #log_level: info
  #debug_listen: "0.0.0.0:8200 ssl http2"
  #request_debug_token: "acqua"
  #upstream_keepalive_pool_size: "5120"

replicaCount: 3
  

ingressController:
  enabled: false
  installCRDs: false

resources:
  requests:
    cpu: 1
    memory: "2Gi"
  limits:
    cpu: 4
    memory: "3Gi"

status:
  enabled: true
  http:
    enabled: true
  containerPort: 8100

#deployment:
#  serviceAccount:
#    create: false
#    name: kaigateway-podid-sa

serviceMonitor:
  enabled: true


nodeSelector:
  "alpha.eksctl.io/nodegroup-name": "node-ai-gateway"

#tolerations:
#- key: "dedicated"
#  value: "kong"
#  effect: "NoSchedule"

securityContext:
  sysctls:
#    - name: net.ipv4.tcp_tw_reuse
#      value: "2"
    #- name: net.core.somaxconn
#      #value: "65535"
    #  value: "5000000"
      #value: "100000"
    #- name: net.ipv4.tcp_max_syn_backlog
    #  value: "65535"
    #  value: "5000000"
    - name: net.ipv4.tcp_max_tw_buckets
      value: "2000"
    - name: net.ipv4.ip_local_port_range
      value: "4000 65535"
    #- name: net.netfilter.nf_conntrack_max
    #  value: "655350"
    #- name: net.netfilter.nf_conntrack_tcp_timeout_established
    #  value: "10"
